### ISSUE TITLE
Uncaught TypeError: validateEventDispatches is not a function

### ISSUE THREAD

**Issue by mackermans** [sanack/atom-jq#42]
1. Install atom-jq
2. Open (project) folder from commandline with `atom -a .`

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.4
**Thrown From**: [atom-jq](https://github.com/sanack/atom-jq) package, v0.6.0
### Stack Trace

Uncaught TypeError: validateEventDispatches is not a function

```
At /Users/maartenackermans/.atom/packages/atom-jq/node_modules/react/lib/EventPluginUtils.js:101

TypeError: validateEventDispatches is not a function
    at Object.executeDispatchesInOrder (/Users/maartenackermans/.atom/packages/atom-jq/node_modules/react/lib/EventPluginUtils.js:101:5)
    at executeDispatchesAndRelease (/Users/maartenackermans/.atom/packages/atom-jq/node_modules/react/lib/EventPluginHub.js:44:22)
    at executeDispatchesAndReleaseTopLevel (/Users/maartenackermans/.atom/packages/atom-jq/node_modules/react/lib/EventPluginHub.js:55:10)
    at Array.forEach (native)
    at forEachAccumulated (/Users/maartenackermans/.atom/packages/atom-jq/node_modules/react/lib/forEachAccumulated.js:25:9)
    at Object.EventPluginHub.processEventQueue (/Users/maartenackermans/.atom/packages/atom-jq/node_modules/react/lib/EventPluginHub.js:221:7)
    at runEventQueueInBatch (/Users/maartenackermans/.atom/packages/atom-jq/node_modules/react/lib/ReactEventEmitterMixin.js:18:18)
    at Object.ReactEventEmitterMixin.handleTopLevel [as _handleTopLevel] (/Users/maartenackermans/.atom/packages/atom-jq/node_modules/react/lib/ReactEventEmitterMixin.js:29:5)
    at handleTopLevelImpl (/Users/maartenackermans/.atom/packages/atom-jq/node_modules/react/lib/ReactEventListener.js:73:24)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/maartenackermans/.atom/packages/atom-jq/node_modules/react/lib/Transaction.js:138:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/maartenackermans/.atom/packages/atom-jq/node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
    at Object.batchedUpdates (/Users/maartenackermans/.atom/packages/atom-jq/node_modules/react/lib/ReactUpdates.js:98:20)
    at ReactEventListener.dispatchEvent (/Users/maartenackermans/.atom/packages/atom-jq/node_modules/react/lib/ReactEventListener.js:150:20)
```
### Commands

```
     -0:32.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:10.6.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-icons.seti-roboto.seti-animate.theme-seti-syntax.theme-seti-ui)
     -0:08.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:08.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:07.7.0 core:close (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-icons.seti-roboto.seti-animate.theme-seti-syntax.theme-seti-ui)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-rubocop",
      "atom-typescript"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-hot-package-loader, v0.5.1
atom-jq, v0.6.0
autocomplete-ruby, v0.1.0
cucumber, v0.5.0
editorconfig, v1.4.1
language-docker, v1.1.6
language-dotenv, v1.0.0
linter, v1.11.10
linter-docker, v0.1.2
linter-js-standard, v3.3.3
linter-markdown, v1.5.2
linter-ruby, v1.2.2
linter-shellcheck, v1.2.0
linter-tslint, v0.10.0
linter-twig, v0.1.1
php-twig, v4.0.0
pigments, vundefined
pretty-json, v1.4.1
ruby-block, v0.3.5
set-syntax, v0.3.0
seti-syntax, v1.0.1
seti-ui, v1.3.1
wakatime, v6.0.8

# Dev
No dev packages
```

**Comment by davesnx** [comment]
@mackermans I made the investigation, and here we go:

You're using `atom-typescript` that loads another version of React, (0.13): [atom-typescript/package.json](https://github.com/TypeStrong/atom-typescript/blob/master/package.json#L70), and It crashes with the `validateEventDispatches is not a function`.

Using react-for-atom should fix it: [react-for-atom](https://www.npmjs.com/package/react-for-atom) or also the Remove react one: https://github.com/sanack/atom-jq/issues/31
I read too that the react 15.0.3 or something fix it, so... I will just try it.

Could you uninstall the typecript plugin and try atom-jq again? :D

**Comment by mackermans** [comment]
@davesnx Actually, `atom-typescript` was already disabled...

**Comment by davesnx** [comment]
But you have it installed @mackermans, dunno for sure that matters tbh.

**Comment by mackermans** [comment]
@davesnx I uninstalled it just be sure, didn't make a difference.

**Comment by davesnx** [comment]
oh okay 😢

**Comment by davesnx** [comment]
Can you test with the latest version (v0.6.1) @mackermans
